name: wp_json_api
description: WordPress and WooCommerce JSON API for Flutter Mobile
version: 0.0.1
homepage: https://woosignal.com
repository: https://github.com/woosignal/flutter-woocommerce-api

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
